// QSeq — Sustainable Identity on Every Thing
// Copyright (c) 2026 Meerv Inc.  Required Notice: https://qseq.app
// Licensed under the PolyForm Noncommercial License 1.0.0 — noncommercial use
// only; reuse requires attribution to Meerv Inc. See LICENSE for terms.
// https://polyformproject.org/licenses/noncommercial/1.0.0/

import 'dart:convert';
import 'dart:io';

import 'package:file_selector/file_selector.dart';

import '../models/batch.dart';
import '../models/combined_label.dart';
import '../models/data_source.dart';
import '../models/symbology.dart';
import 'app_controller.dart';

/// Reads and writes QSeq project files: a well-formatted, externally-editable
/// JSON document holding every raw design parameter, so designs can be hand
/// edited or generated by other tools and reopened here.
class ProjectIo {
  ProjectIo._();

  static const String formatName = 'QSeq Project';
  static const int formatVersion = 1;

  // --- mapping -------------------------------------------------------------

  static Map<String, dynamic> toMap(AppSettings s) {
    final d = s.data;
    return {
      'format': formatName,
      'version': formatVersion,
      'workspace': {
        'mode': s.mode.name,
        'oneDSymbology': s.oneDSymbology.name,
        'twoDSymbology': s.twoDSymbology.name,
        'errorCorrection': s.ecLevel.name,
      },
      'data': {
        'kind': d.kind.name,
        'gtin': d.gtin,
        'serial': d.serial,
        'sgtinFormat': d.sgtinFormat.name,
        'companyPrefixLength': d.companyPrefixLength,
        'digitalLinkDomain': d.digitalLinkDomain,
        'nsn': d.nsn,
        'rawText': d.rawText,
      },
      'print': {
        'dpi': s.dpi,
        'xDimensionMm': s.xDimensionMm,
        'barHeightMm': s.barHeightMm,
      },
      'logo': {
        'sideMm': s.logoSideMm,
        'ecBudget': s.logoEcBudget,
        'ecShare': s.logoEcShare,
        'manual': s.logoManual,
        'imagePath': s.logoImagePath,
      },
      'rulers': {
        'onScreen': s.rulersOnScreen,
        'inExports': s.rulersInExports,
      },
      'label': {
        'arrangement': s.arrangement.name,
        'gapMm': s.labelGapMm,
        'paddingMm': s.labelPaddingMm,
      },
      // prefix/start/zero-pad derive from the data serial itself now (legacy
      // keys are ignored on load).
      'serialization': {
        'count': s.batchCount,
        'copies': s.batchCopies,
        'columns': s.batchColumns,
        'pageFormat': s.pageFormat.name,
        'pageOrientation': s.pageOrientation.name,
      },
    };
  }

  static AppSettings fromMap(Map<String, dynamic> m) {
    Map<String, dynamic> sub(String k) =>
        (m[k] as Map?)?.cast<String, dynamic>() ?? const {};
    final w = sub('workspace');
    final d = sub('data');
    final p = sub('print');
    final lg = sub('logo');
    final lb = sub('label');
    final sr = sub('serialization');
    final ru = sub('rulers');

    double dbl(Object? v, double fb) =>
        v is num ? v.toDouble() : (v is String ? double.tryParse(v) ?? fb : fb);
    int integer(Object? v, int fb) =>
        v is num ? v.toInt() : (v is String ? int.tryParse(v) ?? fb : fb);
    String str(Object? v, String fb) => v is String ? v : fb;

    const def = AppSettings();
    return AppSettings(
      mode: _byName(AppMode.values, w['mode'], def.mode),
      oneDSymbology:
          _byName(Symbology.values, w['oneDSymbology'], def.oneDSymbology),
      twoDSymbology:
          _byName(Symbology.values, w['twoDSymbology'], def.twoDSymbology),
      ecLevel: _byName(QrEcLevel.values, w['errorCorrection'], def.ecLevel),
      data: DataSourceInput(
        kind: _byName(DataSourceKind.values, d['kind'], def.data.kind),
        gtin: str(d['gtin'], def.data.gtin),
        serial: str(d['serial'], def.data.serial),
        sgtinFormat:
            _byName(SgtinFormat.values, d['sgtinFormat'], def.data.sgtinFormat),
        companyPrefixLength:
            integer(d['companyPrefixLength'], def.data.companyPrefixLength),
        digitalLinkDomain:
            str(d['digitalLinkDomain'], def.data.digitalLinkDomain),
        nsn: str(d['nsn'], def.data.nsn),
        rawText: str(d['rawText'], def.data.rawText),
      ),
      dpi: dbl(p['dpi'], def.dpi),
      xDimensionMm: dbl(p['xDimensionMm'], def.xDimensionMm),
      barHeightMm: dbl(p['barHeightMm'], def.barHeightMm),
      logoSideMm: dbl(lg['sideMm'], def.logoSideMm),
      logoEcBudget: dbl(lg['ecBudget'], def.logoEcBudget),
      logoEcShare: dbl(lg['ecShare'], def.logoEcShare).clamp(0.05, 0.5),
      logoManual: lg['manual'] == true,
      logoImagePath: lg['imagePath'] is String ? lg['imagePath'] as String : null,
      rulersOnScreen: ru['onScreen'] is bool
          ? ru['onScreen'] as bool
          : def.rulersOnScreen,
      rulersInExports: ru['inExports'] is bool
          ? ru['inExports'] as bool
          : def.rulersInExports,
      arrangement:
          _byName(LabelArrangement.values, lb['arrangement'], def.arrangement),
      labelGapMm: dbl(lb['gapMm'], def.labelGapMm),
      labelPaddingMm: dbl(lb['paddingMm'], def.labelPaddingMm),
      batchCount: integer(sr['count'], def.batchCount),
      batchCopies: integer(sr['copies'], def.batchCopies),
      batchColumns: integer(sr['columns'], def.batchColumns),
      pageFormat: _byName(PageFormat.values, sr['pageFormat'], def.pageFormat),
      pageOrientation: _byName(
          PageOrientation.values, sr['pageOrientation'], def.pageOrientation),
    );
  }

  static T _byName<T extends Enum>(List<T> values, Object? name, T fallback) {
    if (name is! String) return fallback;
    for (final v in values) {
      if (v.name == name) return v;
    }
    return fallback;
  }

  // --- text <-> settings ---------------------------------------------------

  /// Pretty-printed JSON for the given settings (2-space indent).
  static String encode(AppSettings s) =>
      const JsonEncoder.withIndent('  ').convert(toMap(s));

  static AppSettings decode(String json) =>
      fromMap((jsonDecode(json) as Map).cast<String, dynamic>());

  // --- file dialogs --------------------------------------------------------

  static const _group =
      XTypeGroup(label: 'QSeq Project', extensions: ['qseq', 'json']);

  /// Saves [s] to a user-chosen `.qseq` file. Returns false if cancelled.
  static Future<bool> save(AppSettings s) async {
    final location = await getSaveLocation(
      suggestedName: 'design.qseq',
      acceptedTypeGroups: const [_group],
    );
    if (location == null) return false;
    await File(location.path).writeAsString(encode(s));
    return true;
  }

  /// Opens and parses a project file. Returns null if cancelled or invalid.
  static Future<AppSettings?> open() async {
    final file = await openFile(acceptedTypeGroups: const [_group]);
    if (file == null) return null;
    try {
      return decode(await file.readAsString());
    } catch (_) {
      return null;
    }
  }
}
