// QSeq — Sustainable Identity on Every Thing
// Copyright (c) 2026 Meerv Inc.  Required Notice: https://qseq.app
// Licensed under the PolyForm Noncommercial License 1.0.0 — noncommercial use
// only; reuse requires attribution to Meerv Inc. See LICENSE for terms.
// https://polyformproject.org/licenses/noncommercial/1.0.0/

import 'dart:convert';
import 'dart:io';

import 'package:file_selector/file_selector.dart';

import '../models/batch.dart';
import '../models/combined_label.dart';
import '../models/data_source.dart';
import '../models/label_spec.dart';
import '../models/symbology.dart';
import 'app_controller.dart';

/// Reads and writes QSeq project files: a well-formatted, externally-editable
/// JSON document holding every raw design parameter, so designs can be hand
/// edited or generated by other tools and reopened here.
class ProjectIo {
  ProjectIo._();

  static const String formatName = 'QSeq Project';
  static const int formatVersion = 1;

  // --- mapping -------------------------------------------------------------

  static Map<String, dynamic> toMap(AppSettings s, {LabelSpec? label}) {
    final d = s.data;
    return {
      'format': formatName,
      'version': formatVersion,
      'workspace': {
        'mode': s.mode.name,
        'labelOn': s.labelOn,
        'oneDSymbology': s.oneDSymbology.name,
        'twoDSymbology': s.twoDSymbology.name,
        'errorCorrection': s.ecLevel.name,
      },
      'data': {
        'kind': d.kind.name,
        'gtin': d.gtin,
        'serial': d.serial,
        'sgtinFormat': d.sgtinFormat.name,
        'companyPrefixLength': d.companyPrefixLength,
        'digitalLinkDomain': d.digitalLinkDomain,
        'gtinLength': d.gtinLength,
        'serialize': d.serialize,
        'rawText': d.rawText,
      },
      'print': {
        'dpi': s.dpi,
        'xDimensionMm': s.xDimensionMm,
        'barHeightMm': s.barHeightMm,
      },
      'logo': {
        'sideMm': s.logoSideMm,
        'ecBudget': s.logoEcBudget,
        'ecShare': s.logoEcShare,
        'manual': s.logoManual,
        'imagePath': s.logoImagePath,
      },
      'rulers': {
        'onScreen': s.rulersOnScreen,
        'inExports': s.rulersInExports,
      },
      // One 'label' block shared with the web app: the designer spec's keys
      // (wMm/hMm/on/el/…) plus the desktop combined-label layout keys. Each
      // reader picks the fields it knows.
      'label': {
        'arrangement': s.arrangement.name,
        'gapMm': s.labelGapMm,
        'paddingMm': s.labelPaddingMm,
        if (label != null) ...label.toJson(),
      },
      // prefix/start/zero-pad derive from the data serial itself now (legacy
      // keys are ignored on load).
      'serialization': {
        'count': s.batchCount,
        'copies': s.batchCopies,
        'columns': s.batchColumns,
        'pageFormat': s.pageFormat.name,
        'pageOrientation': s.pageOrientation.name,
      },
    };
  }

  static AppSettings fromMap(Map<String, dynamic> m) {
    Map<String, dynamic> sub(String k) =>
        (m[k] as Map?)?.cast<String, dynamic>() ?? const {};
    final w = sub('workspace');
    final d = sub('data');
    final p = sub('print');
    final lg = sub('logo');
    final lb = sub('label');
    final sr = sub('serialization');
    final ru = sub('rulers');

    double dbl(Object? v, double fb) =>
        v is num ? v.toDouble() : (v is String ? double.tryParse(v) ?? fb : fb);
    int integer(Object? v, int fb) =>
        v is num ? v.toInt() : (v is String ? int.tryParse(v) ?? fb : fb);
    String str(Object? v, String fb) => v is String ? v : fb;

    const def = AppSettings();
    // Web files store the manual dead-space under 'manualMm' (their 'sideMm'
    // is a legacy on-flag); desktop files store the true side in 'sideMm'.
    final manualMm = dbl(lg['manualMm'], 0);
    final sideMm = dbl(lg['sideMm'], def.logoSideMm);
    final modeStr = w['mode'];
    return AppSettings(
      // Web legacy: 'label'/'labelSerial' workspaces = combo + overlay.
      mode: modeStr == 'label'
          ? AppMode.combo
          : modeStr == 'labelSerial'
              ? AppMode.comboSerial
              : _byName(AppMode.values, modeStr, def.mode),
      labelOn: w['labelOn'] == true ||
          modeStr == 'label' ||
          modeStr == 'labelSerial',
      oneDSymbology:
          _byName(Symbology.values, w['oneDSymbology'], def.oneDSymbology),
      twoDSymbology:
          _byName(Symbology.values, w['twoDSymbology'], def.twoDSymbology),
      ecLevel: _byName(QrEcLevel.values, w['errorCorrection'], def.ecLevel),
      data: DataSourceInput(
        kind: _byName(DataSourceKind.values, d['kind'], def.data.kind),
        gtin: str(d['gtin'], def.data.gtin),
        serial: str(d['serial'], def.data.serial),
        sgtinFormat:
            _byName(SgtinFormat.values, d['sgtinFormat'], def.data.sgtinFormat),
        companyPrefixLength:
            integer(d['companyPrefixLength'], def.data.companyPrefixLength),
        digitalLinkDomain:
            str(d['digitalLinkDomain'], def.data.digitalLinkDomain),
        gtinLength: integer(d['gtinLength'], def.data.gtinLength),
        serialize: d['serialize'] as bool? ?? def.data.serialize,
        rawText: str(d['rawText'], def.data.rawText),
      ),
      dpi: dbl(p['dpi'], def.dpi),
      xDimensionMm: dbl(p['xDimensionMm'], def.xDimensionMm),
      barHeightMm: dbl(p['barHeightMm'], def.barHeightMm),
      logoSideMm: manualMm > 0 ? manualMm : sideMm,
      logoEcBudget: dbl(lg['ecBudget'], def.logoEcBudget),
      logoEcShare: dbl(lg['ecShare'], dbl(lg['ecBudget'], def.logoEcShare))
          .clamp(0.05, 0.5),
      logoManual: lg['manual'] == true || manualMm > 0,
      logoImagePath: lg['imagePath'] is String ? lg['imagePath'] as String : null,
      rulersOnScreen: ru['onScreen'] is bool
          ? ru['onScreen'] as bool
          : def.rulersOnScreen,
      rulersInExports: ru['inExports'] is bool
          ? ru['inExports'] as bool
          : def.rulersInExports,
      arrangement:
          _byName(LabelArrangement.values, lb['arrangement'], def.arrangement),
      labelGapMm: dbl(lb['gapMm'], def.labelGapMm),
      labelPaddingMm: dbl(lb['paddingMm'], def.labelPaddingMm),
      batchCount: integer(sr['count'], def.batchCount),
      batchCopies: integer(sr['copies'], def.batchCopies),
      batchColumns: integer(sr['columns'], def.batchColumns),
      pageFormat: _byName(PageFormat.values, sr['pageFormat'], def.pageFormat),
      pageOrientation: _byName(
          PageOrientation.values, sr['pageOrientation'], def.pageOrientation),
    );
  }

  /// The label-designer spec carried in the file's `label` block (the same
  /// JSON shape the web app reads/writes), or null when the file predates it.
  static LabelSpec? labelFromMap(Map<String, dynamic> m) {
    final lb = (m['label'] as Map?)?.cast<String, dynamic>();
    if (lb == null || (lb['wMm'] == null && lb['el'] == null)) return null;
    return LabelSpec()..applyJson(lb);
  }

  static T _byName<T extends Enum>(List<T> values, Object? name, T fallback) {
    if (name is! String) return fallback;
    for (final v in values) {
      if (v.name == name) return v;
    }
    return fallback;
  }

  // --- text <-> settings ---------------------------------------------------

  /// Pretty-printed JSON for the given settings (2-space indent).
  static String encode(AppSettings s, {LabelSpec? label}) =>
      const JsonEncoder.withIndent('  ').convert(toMap(s, label: label));

  static AppSettings decode(String json) =>
      fromMap((jsonDecode(json) as Map).cast<String, dynamic>());

  // --- file dialogs --------------------------------------------------------

  static const _group =
      XTypeGroup(label: 'QSeq Project', extensions: ['qseq', 'json']);

  /// Saves to [toPath] when given (the open project), otherwise asks for a
  /// location. Returns the saved path, or null if cancelled.
  static Future<String?> save(AppSettings s,
      {LabelSpec? label, String? toPath}) async {
    var path = toPath;
    if (path == null) {
      final location = await getSaveLocation(
        suggestedName: 'design.qseq',
        acceptedTypeGroups: const [_group],
      );
      if (location == null) return null;
      path = location.path;
    }
    await File(path).writeAsString(encode(s, label: label));
    return path;
  }

  /// Opens and parses a project file. Returns null if cancelled or invalid.
  static Future<({AppSettings settings, LabelSpec? label, String path})?>
      open() async {
    final file = await openFile(acceptedTypeGroups: const [_group]);
    if (file == null) return null;
    try {
      final m = (jsonDecode(await file.readAsString()) as Map)
          .cast<String, dynamic>();
      return (
        settings: fromMap(m),
        label: labelFromMap(m),
        path: file.path,
      );
    } catch (_) {
      return null;
    }
  }
}
