/// The entrypoint for the **server** environment (pre-rendering).
library;

import 'package:jaspr/dom.dart';
import 'package:jaspr/server.dart';

import 'app.dart';
// Generated by Jaspr — do not edit.
import 'main.server.options.dart';

const _description =
    'QSeq generates Barcodes, QR Codes and Data Matrix codes for SGTINs, '
    'GS1 Digital Links and NATO Stock Numbers — with a print-true size '
    'calculator. Source-available, for Sustainable Identity on Every Thing.';

void main() {
  Jaspr.initializeApp(options: defaultServerOptions);

  runApp(Document(
    title: 'QSeq — Sustainable Identity on Every Thing',
    lang: 'en',
    charset: 'utf-8',
    viewport: 'width=device-width, initial-scale=1.0',
    meta: const {'description': _description},
    head: [
      RawText('<link rel="canonical" href="https://qseq.app/" />'),
      RawText('<meta property="og:type" content="website" />'),
      RawText('<meta property="og:site_name" content="QSeq" />'),
      RawText('<meta property="og:title" content="QSeq — Sustainable Identity on Every Thing" />'),
      RawText('<meta property="og:description" content="Native macOS/Windows &amp; web generator for Barcodes, QR Codes and Data Matrix — SGTINs, GS1 Digital Links, EPC URIs and NATO Stock Numbers, with a print-true physical-size calculator." />'),
      RawText('<meta property="og:url" content="https://qseq.app/" />'),
      RawText('<meta name="twitter:card" content="summary" />'),
      RawText('<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 100 100\'%3E%3Crect width=\'100\' height=\'100\' rx=\'18\' fill=\'%230b0d10\'/%3E%3Cg fill=\'%237cf6c8\'%3E%3Crect x=\'18\' y=\'18\' width=\'20\' height=\'20\'/%3E%3Crect x=\'62\' y=\'18\' width=\'20\' height=\'20\'/%3E%3Crect x=\'18\' y=\'62\' width=\'20\' height=\'20\'/%3E%3Crect x=\'48\' y=\'48\' width=\'10\' height=\'10\'/%3E%3Crect x=\'62\' y=\'62\' width=\'10\' height=\'10\'/%3E%3Crect x=\'72\' y=\'72\' width=\'10\' height=\'10\'/%3E%3C/g%3E%3C/svg%3E" />'),
      RawText('<link rel="stylesheet" href="/styles.css" />'),
      RawText('<script async src="https://www.googletagmanager.com/gtag/js?id=G-015RDZXKP2"></script>'),
      RawText('<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js",new Date());gtag("config","G-015RDZXKP2");</script>'),
      // Copy-to-clipboard for the mission "Source code" button.
      RawText('<script>document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".copybtn").forEach(function(b){var o=b.innerHTML;b.addEventListener("click",function(){var el=document.getElementById(b.getAttribute("data-copy-target"));var t=el?el.textContent.trim():"";navigator.clipboard.writeText(t).then(function(){b.classList.add("copied");setTimeout(function(){b.classList.remove("copied");},1200);});});});});</script>'),
    ],
    body: const App(),
  ));
}
